#!/usr/bin/env bash
# Creates an nginx web sever
sudo apt-get -y update
sudo apt-get -y install nginx
chmod u+x /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
