#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"
    j=1
    while [ $j -le 59 ]
    do
            echo "$j"
            (( j++ ))
    done
    (( i++ ))
done
