#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01
#blocks all incoming traffic except those tcp ports(ssh: 22, https: 443, http: 80)

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
