#!/usr/bin/env bash
#Fixing the container so that Nginx is running as the nginx user.
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
